import { ReactNode } from "react";
import type { Metadata } from "next";
import NextTopLoader from 'nextjs-toploader';

import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import { ScrollToTop } from "@/components/shared/ScrollToTop";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template:
      "%s | Pro Ambiente SAC | Servicios de Fumigación y Saneamiento Ambiental",
    default: "ProAmbiente Website",
  },
  description: "Generated by create next app",
  creator: "Ziphonex Tech",
  generator: "Clean Native Code",
  applicationName: "ProAmbiente Website",
  referrer: "origin-when-cross-origin",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  robots: {
    index: true,
    follow: true,
    nocache: true,
  },
  alternates: {
    canonical: "https://www.proambiente.com.pe",
    languages: {
      "es-PE": "/es-PE",
    },
  },
  verification: {
    google: "google",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="es-PE" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <NextTopLoader 
            color="#19ad00"
            initialPosition={0.08}
            crawlSpeed={200}
            height={5}
            crawl={true}
            showSpinner={true}
            easing="ease"
            speed={200}
            shadow="0 0 10px #19ad00,0 0 5px #19ad00"
          />
        {children}
        <ScrollToTop />
        <Toaster/>
      </body>
    </html>
  );
}
